# Generated by Django 3.1.7 on 2021-03-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vlounge',
        ),
        migrations.DeleteModel(
            name='VloungeMenu',
        ),
    ]
