# Generated by Django 3.1.7 on 2021-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210407_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
