# Generated by Django 3.1.7 on 2021-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_category_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='successful',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
